version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  run-lint:
    docker:
      - image: circleci/node:12
    working_directory: /tmp/src
    steps:
      - checkout
      - run: npm install
      - run: npm ci
      - run: npm run build
      - run: npm run lint
workflows:
  node-linters:
    jobs:
      - run-lint

